import type { NextPage } from "next";
import Head from "next/head";
import { useWorkflowStore } from "@stores/workflow/WorkflowStore";

const Home: NextPage = () => {
  const store = useWorkflowStore();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <h2>Hello World</h2>
        <label htmlFor="name">Workflow Name</label>
        <input
          id="name"
          type="text"
          placeholder="Enter a name for your workflow"
          value={store.name ?? ""}
          onChange={(e) => store.changeName(e.currentTarget.value)}
        />
      </section>
    </div>
  );
};

export default Home;
