name: Run tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [main]

jobs:
  cypress:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          build: npm run build
          start: npm run start
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}